name: "build webpage"

on: 
  push:
    branches:
      - source
  workflow_dispatch:

jobs:
  build:
    runs-on: docker pull python:3.11.9-slim-bullseye
    if: "contains(github.event.head_commit.message, '[build]')"
    steps: 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true
        ref: gh-pages
    
    - name: build
      run: |
        pip install -r requirements.txt
        python build.py

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: master
